//
//  Client.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

class Client: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _fullname: String?
    var _address: [String]?
    var _backName: String?
    var _chineseIDNumber: [String]?
    var _coverName: String?
    var _mobile: [String]?
    
    class func dynamoDBTableName() -> String {
        
        return "auflyer-mobilehub-1884545339-Client"
    }
    
    class func hashKeyAttribute() -> String {
        
        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {
        
        return "_fullname"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
            "_userId" : "userId",
            "_fullname" : "fullname",
            "_address" : "address",
            "_backName" : "backName",
            "_chineseIDNumber" : "chineseIDNumber",
            "_coverName" : "coverName",
            "_mobile" : "mobile",
        ]
    }
}
