//
//  TransacationRecord.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

class TransacationRecord: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _date: String?
    var _time: String?
    var _fullTime: String?
    var _buyer: String?
    var _priceBuyIn: [String]?
    var _priceSellOut: [String]?
    var _productNames: [String]?
    var _store: String?
    
    class func dynamoDBTableName() -> String {

        return "auflyer-mobilehub-1884545339-TransacationRecord"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_date"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_date" : "date",
               "_time" : "time",
               "_fullTime" : "fullTime",
               "_buyer" : "buyer",
               "_priceBuyIn" : "priceBuyIn",
               "_priceSellOut" : "priceSellOut",
               "_productNames" : "productNames",
               "_store" : "store"
        ]
    }
}
